Ros fb conversion test
agri-gaia/seerep pull request #186
Opened 2022-09-28 18:19 UTC by jarkenau

2022-10-18 15:10 UTC, mhoellmann reviewed
please rebase to the master branch or cherry-pick the relevant commits. This PR contains a lot of commits from the previous PR.

2022-10-18 15:10 UTC, mhoellmann commented on seerep-ros/seerep_ros_conversions_fb/test/ros_to_fb_conversion_test.cpp
> +    // Transform End
break this down into multiple methods.

2022-10-18 15:10 UTC, mhoellmann commented on seerep-ros/seerep_ros_conversions_fb/test/ros_to_fb_conversion_test.cpp
> +geometry_msgs::TransformStamped rosToFbConversionTest::converted_t_stamped;
Is this really necessary? Isn't it easier to create an object of the class?
Would the structure of the test benefit from putting everything in the class?

2022-11-10 13:41 UTC, mhoellmann requested changes

2022-11-10 13:41 UTC, mhoellmann commented on seerep-ros/seerep_ros_conversions_fb/test/ros_to_fb_conversion_test.cpp
> +  void TestBody()
Do not use this function according to the gTest documentation. Can you not better call those functions in the constructor?

>   // Runs the test after the test fixture has been set up.
  //
  // A sub-class must implement this to define the test logic.
  //
  // DO NOT OVERRIDE THIS FUNCTION DIRECTLY IN A USER PROGRAM.
  // Instead, use the TEST or TEST_F macro.
  virtual void TestBody() = 0;

2022-11-10 13:41 UTC, mhoellmann commented on seerep-ros/seerep_ros_conversions_fb/test/ros_to_fb_conversion_test.cpp
> +  testHeader(original_header, testClass.converted_header);
Why do you need the "testClass." here but at no other converted object?

2022-11-10 13:41 UTC, mhoellmann commented on seerep-ros/seerep_ros_conversions_fb/test/ros_to_fb_conversion_test.cpp
> +  void TestBody()
Maybe SetUpTestSuite() is the correct methode?

2022-11-23 15:30 UTC, mhoellmann approved these changes

2022-11-23 15:37 UTC, merged

2022-11-25 15:07 UTC, 104H commented
closes #185 and #82