first version for directly dumping ROS messages to HDF5
agri-gaia/seerep pull request #227
Opened 2022-12-07 13:22 UTC by jarkenau

- First step of #201 
- Currently only supports image messages

2022-12-09 10:01 UTC, Mark-Niemeyer requested changes

2022-12-09 13:06 UTC, jarkenau commented on seerep-hdf5/seerep-hdf5-ros/src/hdf5-ros.cpp
> +      std::make_shared<HighFive::File>(path_ + filename_ + ".h5", HighFive::File::ReadWrite | HighFive::File::Create);
I don't know, to which attributes you're referring. What is meant by name? Just use `map` as the root frame?

2022-12-09 13:11 UTC, Mark-Niemeyer commented on seerep-hdf5/seerep-hdf5-ros/src/hdf5-ros.cpp
> +      std::make_shared<HighFive::File>(path_ + filename_ + ".h5", HighFive::File::ReadWrite | HighFive::File::Create);
You can do it like here:

https://github.com/agri-gaia/seerep/blob/a0494a14639e0c99db1fca1d28bb16c2c46b848b/examples/cpp/seerep_ros_communication/src/hdf5dump.cpp#L17-L22

Name = human readable name for the project
and yes, `map` should work as root frame

2022-12-12 09:13 UTC, jarkenau commented
For the future, the `Hdf5Ros` class should inherit from `Hdf5CoreGeneral` and should use:
 https://github.com/agri-gaia/seerep/blob/a0494a14639e0c99db1fca1d28bb16c2c46b848b/seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-general.h#L38 
to write the attributes. It probably also makes sense to add a function to the Core to write arbitrary multidimensional arrays.

2022-12-15 12:21 UTC, Mark-Niemeyer approved these changes

2022-12-15 12:21 UTC, merged