Overall bounding box service
agri-gaia/seerep pull request #241
Opened 2023-01-10 17:27 UTC by 104H

2023-01-13 13:52 UTC, Mark-Niemeyer requested changes

2023-01-13 13:52 UTC, Mark-Niemeyer commented on examples/python/gRPC/meta/gRPC_fb_getOverallBoundingBox.py
> +print("Max Time (Seconds, Nanoseconds): " + str(response.TimeMax().Seconds()) + " ," + str(response.TimeMax().Nanos()))
remove or rename file

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-com/fbs/meta_operations.fbs
> +include "datatype.fbs";
Is this include really needed?

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-msgs/fbs/uuid_datatype_pair.fbs
> +    datatypes:Datatype;
rename to singular

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/include/seerep-core/core-dataset.h
> +  seerep_core_msgs::AABB getSpatialBounds(std::vector<seerep_core_msgs::Datatype> datatypes);
update code docu

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/include/seerep-core/core-project.h
> +  seerep_core_msgs::AABB getSpatialBounds(std::vector<seerep_core_msgs::Datatype> datatypes);
add code docu

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/include/seerep-core/core.h
> +  seerep_core_msgs::AABB getOverallBound(boost::uuids::uuid uuid, std::vector<seerep_core_msgs::Datatype> datatypes);
add code docu

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +  std::vector<seerep_core_msgs::Datatype> dt_vector;
please add a comment why you are using a vector, but only adds one element. Short summary of the problem with the fb enum

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +  seerep_core_msgs::AabbTime timeinterval = seerepCore->getOverallTimeInterval(uuidFromString, dt_vector);
All packages in the seerep-server package should catch all errors. Take a look at the other functions and add the try-catch here

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +  seerep_core_msgs::AABB overallBB = seerepCore->getOverallBound(uuidFromString, dt_vector);
All packages in the seerep-server package should catch all errors. Take a look at the other functions and add the try-catch here

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +  std::vector<seerep_core_msgs::Datatype> dt_vector;
please add a comment why you are using a vector, but only adds one element. Short summary of the problem with the fb enum

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/src/core-dataset.cpp
> +  overalltime.max_corner().set<0>(0);
Shouldn't this be std::numeric_limits<int64_t>::min()  ?

2023-01-13 13:52 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/src/core-dataset.cpp
> +  overallbb.max_corner().set<2>(0);
Shouldn't this be std::numeric_limits\<float>::min() ?

2023-01-13 13:52 UTC, Mark-Niemeyer commented
Also add the pb-interface, please.

2023-01-30 10:34 UTC, Mark-Niemeyer requested changes

2023-01-30 10:34 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/pb-meta-operations.cpp
> +    uint32_t min_seconds = (uint32_t)(mintime >> 32);
double check signed/unsigned

from seerep-msgs/core/timestamp.h:
```
  int32_t seconds;
  uint32_t nanos;
```

2023-01-30 10:34 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/pb-meta-operations.cpp
> +    uint32_t max_seconds = (uint32_t)(maxtime >> 32);
double check signed/unsigned

from seerep-msgs/core/timestamp.h:
```
  int32_t seconds;
  uint32_t nanos;
```

2023-01-30 10:34 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +    uint32_t min_seconds = (uint32_t)(mintime >> 32);
double check signed/unsigned

from seerep-msgs/core/timestamp.h:
```
  int32_t seconds;
  uint32_t nanos;
```

2023-01-30 10:34 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-meta-operations.cpp
> +    uint32_t max_seconds = (uint32_t)(maxtime >> 32);
double check signed/unsigned

from seerep-msgs/core/timestamp.h:
```
  int32_t seconds;
  uint32_t nanos;
```

2023-01-30 10:34 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core/src/core-dataset.cpp
> +  overallbb.max_corner().set<2>(std::numeric_limits<int64_t>::min());
This should also be `float` and not `int64_t`, shouldn't it?

2023-04-26 14:26 UTC, 104H commented
Closed due to erroneous rebase

2023-04-26 14:26 UTC, closed without merging