Correct time(zone) in docker containers
agri-gaia/seerep pull request #244
Opened 2023-01-22 13:19 UTC by jarkenau

The time(zone) in the docker container was not properly set. With this PR, the time will be retrieved from the host system via mounting the respective files. I thought this was the most versatile way. We could also set the timezone explicitly, e.g. in the `docker-compose.yml`: 

```.yml
version: "3.6"
services:
  seerep:
    image: ghcr.io/agri-gaia/seerep_server:latest
    tty: true
    container_name: seerep_server
    command:
      # define data-dir for seerep-server
      - "--data-folder=/mnt/seerep-data"
    ports:
      # the gRPC port
      - 9090:9090
    volumes:
      # set a folder for seerep-data on your host system
      #- /your/local/absolute/path:/mnt/seerep-data
      - seerep-data:/mnt/seerep-data
    environment:
      - TZ=Europe/Berlin
volumes:
  seerep-data:
```

2023-01-23 17:13 UTC, Mark-Niemeyer commented
I'd suggest doing it explicitly with the env var because the mounting already doesn't work for RedHat distributions.

Maybe we should also log the time zone (with a function like [this](https://stackoverflow.com/a/25193900)) during start up (e.g., after or in this [function](https://github.com/agri-gaia/seerep/blob/43436c335cf8b25822a1824a42467428bff49ef1/seerep-srv/seerep-server/src/server.cpp#L10)).

2023-01-24 10:56 UTC, jarkenau commented
The timezone will now be logged like this:

```bash
[2023-01-24 11:55:27.727340]<info>: Current timezone: CET
[2023-01-24 11:55:27.727500]<info>: The used logging folder is: /seerep/seerep-data/log/
[2023-01-24 11:55:27.727539]<info>: The used data folder is: /seerep/seerep-data/
....
```

2023-01-24 13:21 UTC, Mark-Niemeyer requested changes

2023-01-24 15:24 UTC, Mark-Niemeyer approved these changes

2023-01-24 15:24 UTC, merged