Camera intrinsics - First phase of #148
agri-gaia/seerep pull request #260
Opened 2023-03-09 18:22 UTC by 104H

2023-03-09 18:23 UTC, 104H commented
First phase of #148

2023-03-10 12:06 UTC, Mark-Niemeyer requested changes
please also provide a small python script to test the set and get grpc services

2023-03-10 12:06 UTC, Mark-Niemeyer commented on seerep-srv/seerep-server/src/fb-cameraintrinsics-service.cpp
> +  seerep_core_msgs::camera_intrinsics_query ciq_coremsg;
please use try-catch in both services to catch potential errors. Check e.g. fb-image-service.cpp

2023-03-10 12:06 UTC, Mark-Niemeyer commented on seerep-hdf5/seerep-hdf5-core/CMakeLists.txt
> +find_package(gRPC CONFIG REQUIRED)
Do we really need grpc here? The core should be agnostic...

2023-03-23 13:25 UTC, 104H commented on seerep-srv/seerep-server/src/fb-cameraintrinsics-service.cpp
> +  ciCore->getData(ciq_coremsg, ci);
Is the right approach to convert the core msg `ci` to a FB CI and then write it to the writer?

2023-04-11 16:28 UTC, Mark-Niemeyer requested changes

2023-04-11 16:28 UTC, Mark-Niemeyer commented on seerep-srv/seerep-core-fb/src/core-fb-camera-intrinsics.cpp
> +  // CoreFbGeneral::getAllFileAccessorFromCore(m_seerepCore, m_hdf5IoMap);
remove?

2023-04-11 16:28 UTC, Mark-Niemeyer commented on seerep-msgs/fbs/region_of_interest.fbs
> +table regionOfInterest
Start table name with upper case for consistency

2023-04-11 16:28 UTC, Mark-Niemeyer commented on examples/python/gRPC/util_fb.py
> +from fb import regionOfInterest
why is this separately and not in line 3-27?

2023-04-14 14:51 UTC, 104H commented
This pull request was carried forward after a rebase in #273 .

2023-04-14 14:51 UTC, closed without merging