Polygon query
agri-gaia/seerep pull request #308
Opened 2023-07-06 14:34 UTC by 104H

Allow the user to query point cloud data using a polygon instead of a bounding box.

The Polygon has 2D vertices, along with a constant `z` value for all the points and a `height`. The z value defined the position of the 2D polygon along the z axis, and height defines how tall it is.

The user provides, along with this query, a boolean variable called `fullyEncapsulated`. If true, the results returned by the query must be entirely inside the provided polygon. The possibility of their not being fully inside the polygon arises due to the polygon's feature of being irregular. Being able to query irregular spaces (non axis aligned bb / oriented bb) is the principle contribution of this PR.

2023-07-06 16:15 UTC, Mark-Niemeyer requested changes

2023-07-06 16:15 UTC, Mark-Niemeyer commented on seerep_srv/seerep_core/src/core_dataset.cpp
> +        !(polygon.z < bg::get<bg::max_corner, 2>(aabb) && polygon.z + polygon.height > bg::get<bg::max_corner, 2>(aabb)))
should we use `>=` and `<=` here?

2023-07-07 04:51 UTC, 104H commented on seerep_srv/seerep_core/src/core_dataset.cpp
> +        bg::set<0>(min, bg::get<0>(p));
We still need to check the rest of the dimensions even if one of them is updated.

2023-07-24 06:55 UTC, Mark-Niemeyer requested changes

2023-07-24 15:02 UTC, Mark-Niemeyer approved these changes

2023-07-24 15:16 UTC, merged