Feat/query sorted by time
agri-gaia/seerep pull request #348
Opened 2023-11-10 17:12 UTC by Mark-Niemeyer

2023-12-04 12:03 UTC, jarkenau commented
@Mark-Niemeyer what's the status on this PR?

2023-12-11 10:42 UTC, jarkenau requested changes

2023-12-11 10:42 UTC, jarkenau commented on seerep_srv/seerep_core/src/core_dataset.cpp
> +    return sortResultByTimeActualSorting(sortingVector);
Please reuse the code from [sortResultByTime](https://github.com/agri-gaia/seerep/blob/f0c986de31ff366c70b2b698474e7dd30d0030f6/seerep_srv/seerep_core/src/core_dataset.cpp#L427)

2023-12-11 10:42 UTC, jarkenau commented on seerep_srv/seerep_core/src/core_dataset.cpp
> +}
```suggestion
  std::sort(sortingVector.begin(), sortingVector.end());
  std::vector<boost::uuids::uuid> sortedResults;
  sortedResults.reserve(sortingVector.size());
  
  for (auto&  x : sortingVector)
  {
    sortedResults.push_back(std::move(x.second));
  }
  return sortedResults;
}
```

2023-12-11 10:42 UTC, jarkenau commented on seerep_srv/seerep_core/include/seerep_core/core_dataset.h
> +  sortResultByTimeActualSorting(std::vector<std::pair<int64_t, boost::uuids::uuid>>& sortingVector);
Combine these functions? I don't think it makes sense to call them individually, and the naming is not the best.

2023-12-11 10:56 UTC, Mark-Niemeyer commented on .gitignore
> +**/other_packages/**
This allows to add other repos to the other_packages folder when these other repos link to seerep, but aren't part of this repo. This is a quick solution. We should create debian packages or install this repo properly in the long run.

2023-12-15 09:21 UTC, jarkenau approved these changes

2023-12-19 09:23 UTC, merged